"""teams playlists owner_type

Revision ID: 451bbb44d861
Revises: eea8debb81e8
Create Date: 2026-09-07 18:44:00.591451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg


# revision identifiers, used by Alembic.
revision: str = '451bbb44d861'
down_revision: Union[str, None] = 'eea8debb81e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_type', sa.Enum('USER', 'TEAM', name='owner_type'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_problems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('problem_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_problems_playlist_id'), 'playlist_problems', ['playlist_id'], unique=False)
    op.create_index('uq_playlist_problem', 'playlist_problems', ['playlist_id', 'problem_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_owner_id'), 'teams', ['owner_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='team_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index('uq_team_member', 'team_members', ['team_id', 'user_id'], unique=True)
    op.add_column('contests', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('contests', sa.Column('owner_type', sa.Enum('USER', 'TEAM', name='owner_type'), nullable=False, server_default='USER'))
    op.drop_constraint(op.f('contests_owner_id_fkey'), 'contests', type_='foreignkey')
    op.add_column('problems', sa.Column('owner_type', sa.Enum('USER', 'TEAM', name='owner_type'), nullable=False, server_default='USER'))
    op.drop_constraint(op.f('problems_owner_id_fkey'), 'problems', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('problems_owner_id_fkey'), 'problems', 'users', ['owner_id'], ['id'])
    op.drop_column('problems', 'owner_type')
    op.create_foreign_key(op.f('contests_owner_id_fkey'), 'contests', 'users', ['owner_id'], ['id'])
    op.drop_column('contests', 'owner_type')
    op.drop_column('contests', 'is_public')
    op.drop_index('uq_team_member', table_name='team_members')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_teams_owner_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index('uq_playlist_problem', table_name='playlist_problems')
    op.drop_index(op.f('ix_playlist_problems_playlist_id'), table_name='playlist_problems')
    op.drop_table('playlist_problems')
    op.drop_table('playlists')
    # ### end Alembic commands ###
