"""testcase case_id

Revision ID: eea8debb81e8
Revises: 5dd2b5a64fd7
Create Date: 2026-09-07 15:26:55.068320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg


# revision identifiers, used by Alembic.
revision: str = 'eea8debb81e8'
down_revision: Union[str, None] = '5dd2b5a64fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('case_id', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcases', 'case_id')
    # ### end Alembic commands ###
